name: Presubmit.ai with upstream CI steps

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.LLM_API_KEY }}" ]; then
            echo "Error: LLM_API_KEY secret is not configured"
            exit 1
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: npm install

      - name: Create reports directory for CI results
        run: mkdir -p reports

      - name: Run TypeScript Compiler Check
        run: npx tsc --noEmit 2>&1 | tee reports/tsc.txt
        continue-on-error: true

      - name: Upload CI results
        uses: actions/upload-artifact@v4
        with:
          name: ci-results
          path: reports/*.txt

      - uses: kingychiu/ai-reviewer@ci-reading
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: "gemini-1.5-flash"
          CI_REPORTS_DIR: "reports"
