name: Presubmit.ai with upstream CI steps

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Create reports directory
        run: mkdir -p reports
      - name: Write a sample report
        run: echo "This code contain a SQL Injection Risk. Must be fixed." > reports/security.txt
      - name: Upload CI results
        uses: actions/upload-artifact@v4
        with:
          name: ci-results
          path: reports/*.txt

  review:
    runs-on: ubuntu-latest
    # only run this job when the previous job passed
    needs: [ci]
    # always run this job even the upstream job failed
    if: always()
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.LLM_API_KEY }}" ]; then
            echo "Error: LLM_API_KEY secret is not configured"
            exit 1
          fi
      - uses: kingychiu/ai-reviewer@ci-reading
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: "gemini-1.5-flash"
          CI_REPORTS_DIR: "reports"
